title: "Moja Strona"
theme: minima
show_downloads: false
plugins:
  - jekyll-seo-tag

# Konfiguracja nawigacji
header_pages:
  - index.md
  - o-nas.md
  - kontakt.md
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
